/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.tabs;

import business.building.DonativoRealizado;
import business.building.Projeto;
import business.building.Tarefa;
import business.building.VoluntariadoRealizado;
import business.funds.Donativo;
import business.funds.Voluntariado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import ui.AppState;

/**
 *
 * @author ruioliveiras
 */
public class BuilddingToolBar extends javax.swing.JPanel {

    private AppState appState;
    private boolean isSelecting = true;
    private Projeto selectedProject;

    /**
     * Creates new form BuilddingToolBar
     */
    public BuilddingToolBar() {
        initComponents();
    }

    public BuilddingToolBar(AppState appState) {
        initComponents();
        this.appState = appState;
        btnSelectProject.setText("Selecionar Projeto");
    }

    public void btnSelectProjectAction() throws SQLException {
        buttonGroup1.clearSelection();
        if (isSelecting) {
            List<Projeto> l = appState.habitat().projetoGetAll();
            appState.BuildingSelect(Projeto.class, l);
            btnSelectProject.setText("Selecionar Projeto");
        } else {
            selectedProject = appState.get(Projeto.class).listSelected();
            if (selectedProject != null) {
                String name = selectedProject.getDesignacao();
                if (name.length() > 20) {
                    lnName.setToolTipText(name);
                    name = name.substring(0, 17) + " ...";
                    lnName.setText(name);
                }
                lnName.setText(name);
            }
            btnTarefasAction();
            btnSelectProject.setText("Voltar a selecionar");
        }
        btnDonations.setEnabled(!isSelecting);
        btnTarefas.setEnabled(!isSelecting);
        btnVolunters.setEnabled(!isSelecting);

        isSelecting = !isSelecting;
    }

    public void btnTarefasAction() throws SQLException {
        btnTarefas.setSelected(true);
        List<Tarefa> l = selectedProject.getTarefas();
        appState.BuildingSelect(Tarefa.class, l);
    }

    public void btnDonationsAction() throws SQLException {
        btnDonations.setSelected(true);
        List<DonativoRealizado> l = selectedProject.getDonativos();
        appState.BuildingSelect(DonativoRealizado.class, l);
    }

    public void btnVoluntersAction() throws SQLException {
        btnVolunters.setSelected(true);
        List<VoluntariadoRealizado> l = new ArrayList<>();
        List<Tarefa> ts = selectedProject.getTarefas();
        for (Tarefa t : ts) {
            l.addAll(t.getVoluntariado());
        }
        appState.BuildingSelect(VoluntariadoRealizado.class, l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnEndTaks = new javax.swing.JButton();
        btnGeralVison = new javax.swing.JButton();
        btnSelectProject = new javax.swing.JButton();
        lnName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTarefas = new javax.swing.JToggleButton();
        btnDonations = new javax.swing.JToggleButton();
        btnVolunters = new javax.swing.JToggleButton();

        btnEndTaks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/tarefas32.png"))); // NOI18N
        btnEndTaks.setText("Finalizar Tarefa");
        btnEndTaks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnGeralVison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/estatisticas32.png"))); // NOI18N
        btnGeralVison.setText("Visao Geral");
        btnGeralVison.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGeralVison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeralVisonActionPerformed(evt);
            }
        });

        btnSelectProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/editar32.png"))); // NOI18N
        btnSelectProject.setText("Selecionar Projeto");
        btnSelectProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSelectProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProjectActionPerformed(evt);
            }
        });

        lnName.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lnName.setText("Quinta do joaquim");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("Ações");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("Vistas");

        buttonGroup1.add(btnTarefas);
        btnTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/tarefas32.png"))); // NOI18N
        btnTarefas.setText("Tarefas");
        btnTarefas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarefasActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDonations);
        btnDonations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/donativo32.png"))); // NOI18N
        btnDonations.setText("Donativos Utilizados");
        btnDonations.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationsActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnVolunters);
        btnVolunters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/assests/voluntario32.png"))); // NOI18N
        btnVolunters.setText("Voluntariado");
        btnVolunters.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolunters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoluntersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEndTaks, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(btnGeralVison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSelectProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDonations, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(btnVolunters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lnName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectProject)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTarefas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDonations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolunters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeralVison)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEndTaks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeralVisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeralVisonActionPerformed

    }//GEN-LAST:event_btnGeralVisonActionPerformed

    private void btnSelectProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProjectActionPerformed
        try {
                btnSelectProjectAction();
        } catch (SQLException ex) {
            (new ui.util.ExceptionHandler("Erro enquanto carregava Projetos", ex)).fire();
        }
    }//GEN-LAST:event_btnSelectProjectActionPerformed

    private void btnTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefasActionPerformed
        try {
            btnTarefasAction();
        } catch (SQLException ex) {
            (new ui.util.ExceptionHandler("Erro enquanto carregava Tarefas realizadas", ex)).fire();
        }
    }//GEN-LAST:event_btnTarefasActionPerformed

    private void btnDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationsActionPerformed
        try {
            btnDonationsAction();
        } catch (SQLException ex) {
            (new ui.util.ExceptionHandler("Erro enquanto carregava Donativos realizadas", ex)).fire();
        } 

    }//GEN-LAST:event_btnDonationsActionPerformed

    private void btnVoluntersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoluntersActionPerformed
        try {
            btnVoluntersAction();
        } catch (SQLException ex) {
            (new ui.util.ExceptionHandler("Erro enquanto carregava Voluntarios realizadas", ex)).fire();
        }
    }//GEN-LAST:event_btnVoluntersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDonations;
    private javax.swing.JButton btnEndTaks;
    private javax.swing.JButton btnGeralVison;
    private javax.swing.JButton btnSelectProject;
    private javax.swing.JToggleButton btnTarefas;
    private javax.swing.JToggleButton btnVolunters;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lnName;
    // End of variables declaration//GEN-END:variables
}
