/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.familiy.candidatura;

import business.familiy.Candidatura;
import business.familiy.ElementoFamilia;
import business.familiy.Familia;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import ui.util.UIDimension;

/**
 *
 * @author Jose
 */
public class FamilyCandDetalhes extends javax.swing.JPanel implements UIDimension.JDetails<Candidatura> {

    private final FamilyCandQuestoes familyQuestoes;
    private Familia familia;

    /**
     * Creates new form FamilyCandDetalhes
     */
    public FamilyCandDetalhes() {
        initComponents();
        familyQuestoes = new FamilyCandQuestoes(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        DataNascLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NomeLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ElemNomeLabel = new javax.swing.JLabel();
        ElemParenLabel = new javax.swing.JLabel();
        ElemDataNascLabel = new javax.swing.JLabel();
        ElemEstadoLabel = new javax.swing.JLabel();
        ElemOcupaLabel = new javax.swing.JLabel();
        ElemEscolLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NIFLabel = new javax.swing.JLabel();
        dataCriaLabel = new javax.swing.JLabel();
        TelefoneLabel = new javax.swing.JLabel();
        EstadoProcessoLabel = new javax.swing.JLabel();
        MoradaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EstadoLabel = new javax.swing.JLabel();
        DataCandLabel = new javax.swing.JLabel();
        RendimentoLabel = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Agregado Familiar:");

        DataNascLabel.setText("jLabel23");

        jLabel15.setText("Nome do Representante:");

        NomeLabel.setText("NomeLabel");

        jLabel28.setText("Data nascimento:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Detalhes da família");
        jPanel2.add(jLabel1);

        jLabel16.setText("Morada:");

        jButton2.setText("Questionário");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Estado processo:");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Telefone:");

        jSplitPane1.setDividerLocation(120);

        jLabel17.setText("Nome:");

        jLabel19.setText("Parentesco:");

        jLabel20.setText("Data de nascimento:");

        jLabel13.setText("Estado civil:");

        jLabel14.setText("Ocupação:");

        jLabel21.setText("Escolaridade:");

        ElemNomeLabel.setText("jLabel22");

        ElemParenLabel.setText("jLabel23");

        ElemDataNascLabel.setText("jLabel24");

        ElemEstadoLabel.setText("jLabel25");

        ElemOcupaLabel.setText("jLabel26");

        ElemEscolLabel.setText("jLabel27");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ElemNomeLabel)
                    .addComponent(ElemParenLabel)
                    .addComponent(ElemDataNascLabel)
                    .addComponent(ElemEstadoLabel)
                    .addComponent(ElemOcupaLabel)
                    .addComponent(ElemEscolLabel))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ElemNomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ElemParenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ElemDataNascLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ElemEstadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ElemOcupaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ElemEscolLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jLabel29.setText("NIF:");

        jLabel3.setText("Data criação da família:");

        NIFLabel.setText("jLabel21");

        dataCriaLabel.setText("jLabel4");

        TelefoneLabel.setText("TelefoneLabel");

        EstadoProcessoLabel.setText("EstadoProcessoLabel");

        MoradaLabel.setText("MoradaLabel");

        jLabel4.setText("Estado da candidatura:");

        jLabel5.setText("Data da candidatura:");

        jLabel6.setText("Rendimento:");

        EstadoLabel.setText("jLabel7");

        DataCandLabel.setText("jLabel8");

        RendimentoLabel.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NomeLabel)
                                            .addComponent(DataNascLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dataCriaLabel)
                                            .addComponent(EstadoProcessoLabel)
                                            .addComponent(MoradaLabel)
                                            .addComponent(TelefoneLabel)
                                            .addComponent(NIFLabel)
                                            .addComponent(EstadoLabel)
                                            .addComponent(DataCandLabel)
                                            .addComponent(RendimentoLabel)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(NomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(DataNascLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(MoradaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EstadoProcessoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TelefoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(NIFLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataCriaLabel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(EstadoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DataCandLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RendimentoLabel))))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (jList1.getSelectedIndex() == -1){ return;}
        ElementoFamilia c = (ElementoFamilia) jList1.getModel().getElementAt(jList1.getSelectedIndex());
        loadElement(c);
    }//GEN-LAST:event_jList1ValueChanged

    private void loadElement(ElementoFamilia c){
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            ElemNomeLabel.setText(c.getNome());
            ElemDataNascLabel.setText(df.format(c.getDataNascimento().getTime()) + "");
            ElemEscolLabel.setText(c.getEscolaridade());
            ElemEstadoLabel.setText(c.getEstadoCivil());
            ElemParenLabel.setText(c.getParentesco());
            ElemOcupaLabel.setText(c.getOcupacao());        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     familyQuestoes.setVisible(true);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag); //To change body of generated methods, choose Tools | Templates.       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataCandLabel;
    private javax.swing.JLabel DataNascLabel;
    private javax.swing.JLabel ElemDataNascLabel;
    private javax.swing.JLabel ElemEscolLabel;
    private javax.swing.JLabel ElemEstadoLabel;
    private javax.swing.JLabel ElemNomeLabel;
    private javax.swing.JLabel ElemOcupaLabel;
    private javax.swing.JLabel ElemParenLabel;
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JLabel EstadoProcessoLabel;
    private javax.swing.JLabel MoradaLabel;
    private javax.swing.JLabel NIFLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel RendimentoLabel;
    private javax.swing.JLabel TelefoneLabel;
    private javax.swing.JLabel dataCriaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void set(Candidatura c) {
        familia = c.getFamilia();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        NomeLabel.setText(familia.getNomeRepresentante());
        DataNascLabel.setText(df.format(familia.getDataNascimento().getTime()) + "");
        dataCriaLabel.setText(df.format(familia.getDataCriaFam().getTime()) + "");
        MoradaLabel.setText(familia.getMoradaRepresentante());
        NIFLabel.setText(familia.getNif() + "");
        TelefoneLabel.setText(familia.getContactoRepresentate() + "");
        ElemNomeLabel.setText("");
        ElemDataNascLabel.setText("");
        ElemEscolLabel.setText("");
        ElemEstadoLabel.setText("");
        ElemParenLabel.setText("");
        ElemOcupaLabel.setText("");
        EstadoLabel.setText(c.getEstado().name());
        RendimentoLabel.setText(c.getRendimento() + "");
        DataCandLabel.setText(df.format(c.getDataCand().getTime()) + "");
        familyQuestoes.setCandidatura(c);
        
        final List<ElementoFamilia> listaElems = familia.getElementosFamilia();
        jList1.setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                return listaElems.size();
            }

            @Override
            public Object getElementAt(int index) {
                return listaElems.get(index);
            }
        });
        
        if (listaElems.size() >= 1){
            jList1.setSelectedIndex(1);
            loadElement(listaElems.get(0));
        } 

    }

    @Override
    public JPanel getPanel() {
        return this;
    }

    @Override
    public JFrame getFrame() {
        JFrame f = new JFrame();
        f.setContentPane(this);
        return f;
    }
}
